name: DotNet Instrumentation Main Build
on:
  push:
    branches:
      - main
      - "release/v*"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4